// Separate video list - videos contain their own audio
const videos = [
    { title: "Waves", date: "08-12-25", videoUrl: "videos/song01-master (1).MOV" }
];

const songs = [
    { title: "Waves", date: "08-12-25", url: "songs/song01-master (1).mp3" },
    { title: "Nothing I Can Do", date: "17-11-25", url: "songs/song03-master.mp3" },
    { title: "Russian Moon", date: "03-03-25", url: "songs/russianmoon.mp3" },
    { title: "Tycho-2", date: "03-03-25", url: "songs/tycho-2.mp3" },
    { title: "Clavius", date: "03-03-25", url: "songs/clavius.mp3" },
    { title: "Station V", date: "03-03-25", url: "songs/station-v.mp3" },
    { title: "Monitor 77", date: "03-03-25", url: "songs/monitor-77.mp3" },
    { title: "Music for the Mind", date: "24-06-24", url: "songs/music-for-the-mind.mp3" },
    { title: "Cobblestones", date: "13-05-24", url: "songs/cobblestones.mp3" },
    { title: "Interlude", date: "08-04-24", url: "songs/interlude.mp3" },
    { title: "Be OK", date: "18-03-24", url: "songs/be-OK.mp3" },
    { title: "Spring", date: "26-02-24", url: "songs/spring.mp3" },
    { title: "Snowflakes", date: "15-01-24", url: "songs/snow-flakes.mp3" },
    { title: "Easy on The Bass", date: "04-12-23", url: "songs/easy-on-the-bass.mp3" },
    { title: "Little Stevie", date: "06-11-23", url: "songs/little-stevie.mp3" },
    { title: "The Way You Are", date: "09-10-23", url: "songs/the-way-you-are.mp3" },
    { title: "Everyday Things", date: "18-09-23", url: "songs/everyday-things.mp3" },
    { title: "Do Not Disturb", date: "21-08-23", url: "songs/do-not-disturb.mp3" },
    { title: "Infant Eyes", date: "07-08-23", url: "songs/infant-eyes.mp3" },
    { title: "Switch", date: "24-07-23", url: "songs/switch.mp3" },
    { title: "Bridge", date: "15-05-23", url: "songs/bridge.mp3" },
    { title: "Birds", date: "03-04-23", url: "songs/birds.mp3" },
    { title: "Tail Press", date: "03-04-23", url: "songs/tail-press.mp3" },
    { title: "Bright Future Ahead", date: "06-03-23", url: "songs/bright-future-ahead.mp3" },
    { title: "Happy Sad", date: "23-01-23", url: "songs/happy-sad.mp3" },
    { title: "Nishinomiya", date: "02-01-23", url: "songs/nishinomiya.mp3" },
    { title: "Van Life", date: "12-12-22", url: "songs/van-life.mp3" },
    { title: "Cabinet of Curiousities", date: "21-11-22", url: "songs/chamber-of-curiosity.mp3" },
    { title: "Rosy Retrospection feat. vhsgus", date: "12-11-22", url: "songs/rosy-retrospection.mp3" },
    { title: "Sunday Morning", date: "17-10-22", url: "songs/sunday-morning.mp3" },
    { title: "Jeanne", date: "26-09-22", url: "songs/jeanne.mp3" },
    { title: "Reality Check", date: "29-08-22", url: "songs/reality-check.mp3" },
    { title: "Leisure Skating", date: "01-08-22", url: "songs/leisure-skating.mp3" },
    { title: "Personal Monopoly", date: "04-07-22", url: "songs/personal-monopoly.mp3" },
    { title: "Shells and Corals", date: "06-06-22", url: "songs/shells-and-corals.mp3" },
    { title: "At Midnight", date: "16-05-22", url: "songs/at-midnight.mp3" },
    { title: "Notable People", date: "25-04-22", url: "songs/notable-people.mp3" },
    { title: "International Art History", date: "11-04-22", url: "songs/international-art-history.mp3" },
    { title: "Former Pro", date: "23-03-22", url: "songs/former-pro.mp3" },
    { title: "Genuine Curiosity", date: "16-02-22", url: "songs/genuine-curiosity.mp3" },
    { title: "Beginner's Mind", date: "12-01-22", url: "songs/beginner's-mind.mp3" },
    { title: "Awkward Silence", date: "23-12-21", url: "songs/awkward-silence.mp3" },
    { title: "Together Alone", date: "03-11-21", url: "songs/together-alone.mp3" },
    { title: "Road Trip", date: "24-09-21", url: "songs/road-trip.mp3" },
    { title: "Mark 2", date: "27-08-21", url: "songs/mark-2.mp3" },
    { title: "fomo", date: "16-07-21", url: "songs/fomo.mp3" },
    { title: "Mark 1", date: "25-06-21", url: "songs/mark-1.mp3" },
    { title: "FUD", date: "04-06-21", url: "songs/fud.mp3" },
    { title: "Rewnd", date: "14-05-21", url: "songs/rewnd.mp3" },
    { title: "Thnkng", date: "23-04-21", url: "songs/thnkng.mp3" },
    { title: "doppr", date: "02-04-21", url: "songs/doppr.mp3" },
    { title: "Barbrshop", date: "21-03-21", url: "songs/barbrshop.mp3" },
    { title: "Shortsqueeze", date: "19-02-21", url: "songs/short-squeeze.mp3" },
    { title: "Buttr", date: "29-01-21", url: "songs/buttr.mp3" },
    { title: "Sempai", date: "15-01-21", url: "songs/sempai.mp3" },
    { title: "Rookiemistake", date: "01-01-21", url: "songs/rookie-mistake.mp3" },
    { title: "Ahuacatl", date: "18-12-20", url: "songs/ahuacatl.mp3" },
    { title: "Lazy Sunday", date: "02-12-20", url: "songs/lazy-sunday.mp3" },
    { title: "UFU", date: "18-11-20", url: "songs/UFU.mp3" },
    { title: "addseoul", date: "04-11-20", url: "songs/addseoul.mp3" },
    { title: "Mattari", date: "28-10-20", url: "songs/mattari.mp3" },
    { title: "Sonder", date: "21-10-20", url: "songs/sonder.mp3" },
    { title: "Memories", date: "07-10-20", url: "songs/memories.mp3" },
    { title: "Platform Two", date: "18-09-20", url: "songs/platform-two.mp3" },
    { title: "Nord XL", date: "18-09-20", url: "songs/nordXL.mp3" },
    { title: "Blue MK", date: "18-09-20", url: "songs/blueMK.mp3" },
    { title: "Oceanstrategy", date: "18-09-20", url: "songs/oceanstrategy.mp3" },
    { title: "Heaven", date: "18-09-20", url: "songs/someclouds.mp3" },
    { title: "15122016_v2", date: "15-12-16", url: "songs/15122016.mp3" },
    { title: "beat1304", date: "08-05-16", url: "songs/beat1304.mp3" },
    { title: "Dilution", date: "13-04-16", url: "songs/Dilution.mp3" },
    { title: "112 - Dance With Me (Radiocosmo Soul Injection)", date: "09-10-14", url: "songs/112-dance-with-me-radiocosmo-soulinjection.mp3" },
    { title: "Sunday Loop", date: "16-09-14", url: "songs/sunday-loop.mp3" },
    { title: "Moodswing", date: "08-08-14", url: "songs/moodswing.mp3" },
    { title: "Just Friends", date: "09-06-14", url: "songs/just-friends.mp3" }
];